################
# GitLabCI template for Drupal projects.
#
# This template is designed to give any Contrib maintainer everything they need to test, without requiring modification.
# It is also designed to keep up to date with Core Development automatically through the use of include files that can be centrally maintained.
# As long as you include the project, ref and three files below, any future updates added by the Drupal Association will be used in your
# pipelines automatically. However, you can modify this template if you have additional needs for your project.
# The full documentation is on https://project.pages.drupalcode.org/gitlab_templates/
################

# For information on alternative values for 'ref' see https://project.pages.drupalcode.org/gitlab_templates/info/templates-version/
# To test a Drupal 7 project, change the first include filename from .main.yml to .main-d7.yml
include:
  - template: Security/SAST.gitlab-ci.yml
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

################
# Pipeline configuration variables are defined with default values and descriptions in the file
# https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
# Uncomment the lines below if you want to override any of the variables. The following is just an example.
################
variables:
  SKIP_CSPELL: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_PREVIOUS_MINOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_MAX_PHP: 1
  RUN_JOB_UPGRADE_STATUS: 0

phpunit (coverage):
  extends: phpunit
  rules:
    - if: '$SKIP_PHPUNIT == "1"'
      when: never
    - when: on_success
  before_script:
    # Install and enable PCOV.
    - echo -e '[pcov]\npcov.directory=.' > /usr/local/etc/php/conf.d/pcov.ini
    - docker-php-ext-enable pcov
  variables:
    REPORT_COVERAGE: "true"
    _PHPUNIT_CONCURRENT: 0
    _PHPUNIT_EXTRA:
      value: --coverage-cobertura $CI_PROJECT_DIR/coverage.xml --coverage-text --colors=never --coverage-html $CI_PROJECT_DIR/coverage
  coverage: /^\s*Lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - junit.xml
      - apache.access.log.txt
      - $BROWSERTEST_OUTPUT_DIRECTORY
      - coverage.xml
      - coverage

phpunit:
  rules:
    - when: never

upgrade status:
  allow_failure: true
  rules:
    - when: manual

# Use gitlab-advanced-sast for comprehensive PHP/JS scanning
gitlab-advanced-sast:
  stage: test
  variables:
    # Only scan the visitors module source code
    SAST_EXCLUDED_PATHS: "vendor/, web/"
    # Limit search depth to focus on module code
    SEARCH_MAX_DEPTH: 5

# Use semgrep-sast for additional language support (limited scope)
semgrep-sast:
  stage: test
  variables:
    # Only scan the visitors module source code
    SAST_EXCLUDED_PATHS: "vendor/, web/"
    # Limit search depth to focus on module code
    SEARCH_MAX_DEPTH: 5